-- Database: GreenShareDB

-- DROP DATABASE "GreenShareDB";

CREATE DATABASE "GreenShareDB"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
    
CREATE SEQUENCE CLIMATE_SEQ START 1;	
CREATE SEQUENCE GROWTH_SEQ START 1;	
CREATE SEQUENCE ADDRESS_SEQ START 1;	
CREATE SEQUENCE SPECIES_SEQ START 1;	
CREATE SEQUENCE FLOWER_SEQ START 1;	
CREATE SEQUENCE FLOWER_SHOP_SEQ START 1;	
CREATE SEQUENCE FRUIT_SEQ START 1;	
CREATE SEQUENCE OFFER_SEQ START 1;	
CREATE SEQUENCE PERMISSION_SEQ START 1;	
CREATE SEQUENCE ACHIEVEMENT_SEQ START 1;	
CREATE SEQUENCE REQUEST_SEQ START 1;	
CREATE SEQUENCE SOIL_SEQ START 1;	
CREATE SEQUENCE SUGGESTION_SEQ START 1;	
CREATE SEQUENCE USER_SEQ START 1;	
CREATE SEQUENCE USER_SOIL_SEQ START 1;
CREATE SEQUENCE MONTH_SEQ START 1;